### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kotowata** [kotowata/20240729_art_app#18]

**Comment by kotowata** [comment]
### 概要
訪れた美術館（展覧会）のポスター写真を投稿・閲覧ができるアプリです。

### 実装予定の機能
- [ ] ユーザー登録
- [ ] 投稿機能
- [ ] お気に入り、リスト作成機能
- [ ] 検索機能
- [ ] 開催中イベントのピックアップ
- [ ] 位置情報表示機能

### 必要なページ
- [ ] トップ画面
- [ ] ログイン画面
- [ ] ホーム画面
- [ ] 投稿一覧画面
- [ ] 自分の投稿一覧画面
- [ ] 新規投稿画面
- [ ] 投稿編集画面
- [ ] 投稿詳細画面
- [ ] プライバシーポリシー
- [ ] 利用規約

**Comment by Tsuchiya2** [comment]
<img width="644" alt="image" src="https://github.com/user-attachments/assets/71abfce0-967d-43dc-8417-af72cd097385">

Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態での提出をお願いいたします。

**Comment by kotowata** [comment]
ご確認ありがとうございます。
リンクさせられていなかったようです。
更新しましたのでご確認お願いいたします。
[![Image from Gyazo](https://i.gyazo.com/832f9bd6e2c2d820503041b6dcfd7222.png)](https://gyazo.com/832f9bd6e2c2d820503041b6dcfd7222)

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下MVP後でも良いかと思ったものになります。
- 利用規約・プライバシーポリシー
- マイページ
- いいね・リスト
- タグ付け
- パスワード再発行

**Comment by kotowata** [comment]
ご確認ありがとうございます！
上記承知しました。上記そぎ落としてまずはMVP目指します。
