### ISSUE TITLE
【レビュー依頼】MVPリリース

### ISSUE THREAD

**Issue by kotowata** [kotowata/20240729_art_app#52]

**Comment by kotowata** [comment]
## 各種情報
アプリ名：ArtSpotly
URL：https://two0240729-art-app.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
- [x] 美術展ポスター写真投稿
- [x] 美術展情報記載
- [x] 投稿編集
- [x] 投稿削除
- [x] 投稿詳細
- [x] タイトル・投稿文検索
- [x] 開催中イベントのピックアップ

## READMEレビュー時から変更した機能
投稿内容にイベント住所の入力欄を設ける予定でしたが、ユーザーへの負担になると考え、都道府県のみの選択欄に変更しました。

## サービスイメージがわかるようなスクリーンショット等
- 投稿一覧画面（未ログインでアクセス可能）
[![Image from Gyazo](https://i.gyazo.com/c0cc224c1d98795b8326871203815189.png)](https://gyazo.com/c0cc224c1d98795b8326871203815189)
- 投稿詳細画面
[![Image from Gyazo](https://i.gyazo.com/8fcb9826c4630e949397b68dbd53bab3.png)](https://gyazo.com/8fcb9826c4630e949397b68dbd53bab3)
- 新規投稿画面
[![Image from Gyazo](https://i.gyazo.com/a123ecce44fccdf814e12eb0366b9a37.png)](https://gyazo.com/a123ecce44fccdf814e12eb0366b9a37)
- ログイン機能
[![Image from Gyazo](https://i.gyazo.com/e31c7af9ad60888e7d85a8328021ddef.png)](https://gyazo.com/e31c7af9ad60888e7d85a8328021ddef)
- ページネーション
[![Image from Gyazo](https://i.gyazo.com/e90f9a382eadc990ea390f0dbc992b9d.png)](https://gyazo.com/e90f9a382eadc990ea390f0dbc992b9d)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by kotowata** [comment]
ありがとうございます！！
無事LGTMいただけて嬉しいです！
上記参考に、本リリース目指して引き続きがんばります！！
